[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.usb_mode = 1
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4