[platformio]
default_envs = lolin_s2_mini_20x4

[env_base]
platform = espressif32
board = lolin_s2_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.usb_mode = 1
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

[env:lolin_s2_mini_20x4]
extends = env_base
build_flags = -DLCD_COLS=20 -DLCD_ROWS=4

[env:lolin_s2_mini_16x2]
extends = env_base
build_flags = -DLCD_COLS=16 -DLCD_ROWS=2
